name: fastforward
favicon: null
layout_spectrum: 0.9318927570711821
typography_spectrum: 0.9327967106364667
title: 'Home of Fast Forward Analytics, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3705294707324356
  lightness: 0.8976502309087664
  saturation: 0.6240257932804525
  rhythmicContrast: 0.38953879615291953
purpose: []
