name: Fast Forward
favicon: null
layout_spectrum: 0.99579
typography_spectrum: 0.67608
title: 'Virtual Home of Fast Forward Analytics, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#282828'
    - '#b6b6b6'
    - '#6d6d6d'
  brandStrength: 0.625
  lightness: 0.8976502309087664
  saturation: 0.6240257932804525
  rhythmicContrast: 0.75
purpose: []
